### ISSUE TITLE
Links don’t update URL with #hash

### ISSUE THREAD

**Issue by pepelsbey** [hsnaydd/moveTo#10]
Though it’s nice to have a slow scroll to the ID on a page, the whole point of such anchors is to keep URL updated with current page fragment ID you’ve just been scrolled to. By removing built-in functionaity you make such links less accessible by users. Buttons and links are two different things even if you could make them look similar with JS.

Please add some History API magic or figure out a way to have ID to be added to URL but prevent page from jumping. Otherwise this script should be considered harmful to web UX.

**Comment by hsnaydd** [comment]
Hi @pepelsbey 

Thank you for suggestion, but I don't think this is a task that this plugin has to do. In my opinion, small plugins like MoveTo should do one job and do it well. You can do the things you mentioned with callback function easly. MoveTo is an extensible plugin, depending on your purpose. 

Thank you

**Comment by pepelsbey** [comment]
It’s totally doing one job only, but it replaces behaviour that’s doing two jobs: scrolling (or rather jumping) and keeping URL updated. Both important for UX. So you’re downgrading experience instead of enhancing it.

Of course it’s up to you, I’m not demanding anything here. I’m not even your user, I just came around from [Rachel Nabors’ tweet](https://twitter.com/rachelnabors/status/872136408395374594) to see if it’s good. But then I realized that it doesn’t care enough about web UX and Rachel [agreed with me](https://twitter.com/rachelnabors/status/872193281622278144):

> Argh, that's a big no go for me!
> Hope it'll get fixed! I love anchors, too!

Defaults options are longest to stay, so I expect 99% of users of your library breaking UX with non-updating URLs instead of taking extra mile and figuring out History API in callback. But you can help them with that.

The best possible way to do what you’re trying to achieve here is to enhance experience, e.g keep existing behaviour intact (or mimic it) and make it work better by introducing smooth scrolling instead of immediate jump.

I hope you’ll decide to make moveTo UX even better. Cheers.

**Comment by hsnaydd** [comment]
Hi @pepelsbey 

As I said above I don't think this is a task that this plugin has to do. Actually this is not an anchor scroll plugin. It is a library that you can use while doing it.

It can be added as an example in the future but  I do not think It is a good idea to add it to the source code.

Thank you.

**Comment by iamdubx** [comment]
@hsnaydd please add example that keeps anchors, this feature is must-have, and I don't know History API.

**Comment by amadeann** [comment]
Here's a simple way to replace add the hash location:

```
window.moveTo = new MoveTo({
    callback: function (target) {
        if (target.id !== undefined) {
            window.location.replace("#" + target.id);
        }
    }
});
```
