### ISSUE TITLE
Scroll inner div

### ISSUE THREAD

**Issue by ashgaliyev** [hsnaydd/moveTo#16]
Is it possible to scroll specified element inside some container as it possible by setting `scrollTop` of the container?
For example: https://jsfiddle.net/9exs4Lan/

**Comment by hsnaydd** [comment]
Hi @ashgaliyev 
Unfortunately, there is no way to do this right now. The plugin currently only smooth scrolling to the anchor, but this feature can be considered.

Sory for the late reply, thanks.
