### ISSUE TITLE
Top margin of the first section ignored when scroll to top

### ISSUE THREAD

**Issue by Gillesvk** [hsnaydd/moveTo#33]
In my case, the top margin of the first section is ignored when scroll back to top. I have to use padding instead of margin or wrap the sections in a container div.

NOT WORKING : 

```
<body>
      <section></section>
      <section></section>
      <section></section>
      <button>Back to top</button>
</body>

section {
      margin: 50px 0 0 0;
}
```

WORKING : 

```
<body>
      <section></section>
      <section></section>
      <section></section>
      <button>Back to top</button>
</body>

section {
      padding: 50px 0 0 0;
}
```

OR

```
<body>
      <div class="wrapper">
            <section></section>
            <section></section>
            <section></section>
            <button>Back to top</button>
      </div>
</body>

section {
      margin: 50px 0 0 0;
}
```

**Comment by hsnaydd** [comment]
Hi @Gillesvk

Can you show me an example on [CodePen](codepen.io/) ?

**Comment by Gillesvk** [comment]
Here is a link to a very simple example : [codepen](https://codepen.io/Gillesvk/pen/ExxamBr)
As you will see, the top margin of the first section is ignored.

**Comment by hsnaydd** [comment]
This is not a bug, it's a normal css behavior. The first section's margin is collapsing. You can check [this link](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) for more information.

**Comment by Gillesvk** [comment]
Actually, it's not a margin collapsing issue because I apply only top margin on the child elements of the body, so there is no adjacent margin interference. In the [codepen](https://codepen.io/Gillesvk/pen/ExxamBr), I changed the background color of the body to pink and, as expected, the body contains the top margin of the first section. 

Maybe, it's something to do with the choice between : 
- window.scrollY, 
- window.pageYOffset, 
- document.body.scrollTop, 
- document.documentElement.scrollTop

See this [link](https://inneka.com/programming/js/body-scrolltop-vs-documentelement-scrolltop-vs-window-pageyoffset-vs-window-scrolly/)

**Comment by hsnaydd** [comment]
Check this [codepen](https://codepen.io/hsnaydd/pen/GRRpRGj);

I added

```
display: flex;
flex-direction: column
```
to the body to prevent margin collapsing. As I said before, It seems like this is margin collapsing. Also you can see it clearly with inspect in the browser,

**Comment by hsnaydd** [comment]
You're welcome @Gillesvk , have a nice day :wink:
