### ISSUE TITLE
Incorrectly looking target

### ISSUE THREAD

**Issue by vjik** [hsnaydd/moveTo#34]
Register trigger, then change ID to another target. Transition is carried out to previous target.

I think need move target (https://github.com/hsnaydd/moveTo/blob/master/src/moveTo.js#L94) into listener (https://github.com/hsnaydd/moveTo/blob/master/src/moveTo.js#L103).

**Comment by hsnaydd** [comment]
Hi @vjik 
Tracking changes in DOM is not in the scope of this plugin. You should handle the click event yourself and use the `move` method.

**Comment by vjik** [comment]
No need tracking. Need define target on click, but not on register trigger.

Much nicer `moveTo.registerTrigger(el);` that this:
```
el.addEventListener('click', function(e) {
	e.preventDefault();
	moveTo.move(document.getElementById(el.getAttribute('href').substring(1)));
});```

**Comment by hsnaydd** [comment]
Then we need to reach the DOM and manipulate the string on every click. This is not good for performance. Because your situation is so rare, we should not do this. Also, there is another way to do this.

**Comment by vjik** [comment]
I has several arguments)

1) User click on several links on page, but moveto found targets for ALL links in one moment of time. This is bad for performance.

2) Default behaviour of browsers: find target on click, not on load.

**Comment by hsnaydd** [comment]
The method name is the "register" trigger, that means if you have registered something, you don't have to worry about it if it has changed or not. 

Yes, the `registerTrigger` method stores every target when called. You don't like it? Use the `move`  method instead of it. Also, there is no way to register a trigger with browser scroll APIs.

**Comment by vjik** [comment]
`registerTrigger` use for make smooth scroll on click to link. But it changes the standard link navigation logic. That's the problem.
