### ISSUE TITLE
SyntaxError: Unexpected token: punc ()) - version 1.5.2

### ISSUE THREAD

**Issue by steriley** [hsnaydd/moveTo#6]
I'm currently including moveto in a project and it appears to work great in development.

However when I attempt a production build with webpack it will throw an error from Uglify:
`ERROR in vendor.js from UglifyJs`
`SyntaxError: Unexpected token: punc ()) [vendor.js:xx,xx]`

commenting out the import will allow the build to be successful:
`import MoveTo from 'moveto';`

Any help appreciated.

**Comment by hsnaydd** [comment]
Hi @steriley 
I gues your development evnviroment doesnt has support for ES2015. But It is my fault. I will fix this problem. 

Thanks for your report.
