### ISSUE TITLE
Focus remains on button

### ISSUE THREAD

**Issue by shikkaba** [hsnaydd/moveTo#9]
Clicking on the button in your demo does indeed bring you back to top visually, but the focus remains on the button. The focus should move to wherever the page visually scrolls to instead of staying with the button clicked.

**Comment by hsnaydd** [comment]
Hi @shikkaba 

You can do it by yourself. 

```js
const moveTo = new MoveTo();
const trigger = document.getElementsByClassName('js-trigger')[0];

moveTo.registerTrigger(trigger, function(target){
  trigger.blur();
  if (target instanceof HTMLElement) {
     target.focus();
  }
});
```

**Comment by shikkaba** [comment]
Thank you for writing this, but I'm just saying that this would be a good thing to have in the script as well.

**Comment by hsnaydd** [comment]
Hi @shikkaba 

Thank you for your sugesstion but, I am not sure this is a task that the plugin should do. I dont want to make this plugin complicated. I want to keep it simple and lightweight. 

Thank you.

**Comment by iamdubx** [comment]
@hsnaydd by "not making it complicated" you make it even more complicated for others people to use. The code above doesn't work for me.

```js
const moveTo = new MoveTo()
    const triggers = document.getElementsByClassName('js-trigger')
    for (var i = 0; i < triggers.length; i++) {
      moveTo.registerTrigger(triggers[i], function (target) {
        triggers[i].blur()
        if (target instanceof HTMLElement) {
          target.focus()
        }
      })
    }
```
`Uncaught TypeError: Cannot read property 'blur' of undefined`

**Comment by iamdubx** [comment]
Callback doesn't return an element in the loop. It return `undefined` or 4 (I got 4 elements). It doesn't return actual element!

**Comment by hsnaydd** [comment]
Hi @iamdubx 
Can you show me an example on [jsfiddle](jsfiddle.net) ?

**Comment by iamdubx** [comment]
@hsnaydd sure, here - https://jsfiddle.net/Ltstnk0s/

**Comment by hsnaydd** [comment]
Hi @iamdubx 

Check this;
https://jsfiddle.net/Ltstnk0s/1/
